name: stats
dependencies:
  - pytorch
  - pytorch=1.7.1
  - torchvision
  - cudatoolkit=11.0
  - ftfy
  - regex
  - tqdm
  - pip
  - pip:
    - streamlit
    - streamlit-cropper
    - git+https://github.com/openai/CLIP.git